### ISSUE TITLE
Extra linefeeds when printing form CP/M

### ISSUE THREAD

**Issue by m0jek** [taylorza/zxn-wifiprn#2]
I have noticed that extra linefeeds are printed when printing from CP/M through zxn-wifiprn.

**Comment by taylorza** [comment]
I was never able to print using the printer driver from CP/M however, I have not tested that on the latest releases, I will build a new image and test that as soon as possible.

**Comment by taylorza** [comment]
@m0jek, I think I know what is going on here.

I created a file in CP/M and then dumped the file and I see CP/M is using CR+LF as a line end. Files on the Next end the lines with CR. Since the printer expects CR+LF, I am automatically adding an LF when the driver receives a CR. Net result, on CP/M the printer is receiving CR+LF+LF.

I will add an option to enable/disable CR translation.

**Comment by m0jek** [comment]
Hi, 
Yes I was looking at the assembler lastnight and saw that. Was thinking the same 😉

**Comment by taylorza** [comment]
The latest release has a new driver option that can be used to disable the automatic translation of CR to CRLF. This should now cover the cases for CP/M.

Use the following command to disable the CR translation 
```
DRIVER 80,2,1
```

To re-enable the translation
```
DRIVER 80,2,0
```

**Comment by m0jek** [comment]
Thank you, I will try it out tomorrow morning, UK time.

**Comment by m0jek** [comment]
Hi,

I can confirm the changes work for me too. Thank you for adding the CR translation selection. Much appreciated.

**Comment by taylorza** [comment]
Great, thanks for reporting the issue!
